/* 리뷰 */
CREATE TABLE REVIEW (
	REVIEW_NO INTEGER NOT NULL, /* 리뷰번호 */
	SELLER_ID VARCHAR2(20) NOT NULL, /* 판매자 아이디 */
	USER_ID VARCHAR2(20) NOT NULL, /* 작성자 아이디 */
	GRADE INTEGER, /* 평가점수 */
	REVIEW_CONTENT CLOB, /* 리뷰내용 */
	REG_DT DATE /* 작성일자 */
);

COMMENT ON TABLE REVIEW IS '리뷰';

COMMENT ON COLUMN REVIEW.REVIEW_NO IS '리뷰번호';

COMMENT ON COLUMN REVIEW.SELLER_ID IS '판매자 아이디';

COMMENT ON COLUMN REVIEW.USER_ID IS '작성자 아이디';

COMMENT ON COLUMN REVIEW.GRADE IS '평가점수';

COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS '리뷰내용';

COMMENT ON COLUMN REVIEW.REG_DT IS '작성일자';

CREATE UNIQUE INDEX PK_REVIEW
	ON REVIEW (
		REVIEW_NO ASC
	);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT PK_REVIEW
		PRIMARY KEY (
			REVIEW_NO
		);

/* 회원 */
CREATE TABLE USER (
	USER_ID VARCHAR2(20) NOT NULL, /* 아이디 */
	PASSWORD VARCHAR2(16) NOT NULL, /* 비밀번호 */
	NAME VARCHAR2(30), /* 회원명 */
	NICKNAME VARCHAR2(30), /* 닉네임 */
	HP VARCHAR2(30), /* 핸드폰번호 */
	ADMIN VARCHAR2(5), /* 관리자구분 */
	DROP VARCHAR2(5), /* 탈퇴여부 */
	BLACKLIST VARCHAR2(5) /* 블랙리스트 처분 */
);

COMMENT ON TABLE USER IS '회원';

COMMENT ON COLUMN USER.USER_ID IS '아이디';

COMMENT ON COLUMN USER.PASSWORD IS '비밀번호';

COMMENT ON COLUMN USER.NAME IS '회원명';

COMMENT ON COLUMN USER.NICKNAME IS '닉네임';

COMMENT ON COLUMN USER.HP IS '핸드폰번호';

COMMENT ON COLUMN USER.ADMIN IS '관리자구분';

COMMENT ON COLUMN USER.DROP IS '탈퇴여부';

COMMENT ON COLUMN USER.BLACKLIST IS '블랙리스트 처분';

CREATE UNIQUE INDEX PK_USER
	ON USER (
		USER_ID ASC
	);

ALTER TABLE USER
	ADD
		CONSTRAINT PK_USER
		PRIMARY KEY (
			USER_ID
		);

/* 판매자신고 */
CREATE TABLE USER_REPORT (
	REPORT_NO INTEGER NOT NULL, /* 신고 번호 */
	REPORT_CONTENT CLOB, /* 신고내용 */
	USER_ID VARCHAR2(20) NOT NULL, /* 신고자 아이디 */
	REG_DT DATE, /* 신고일시 */
	DISPOSITION VARCHAR2(5) /* 처분여부 */
);

COMMENT ON TABLE USER_REPORT IS '판매자신고';

COMMENT ON COLUMN USER_REPORT.REPORT_NO IS '신고 번호';

COMMENT ON COLUMN USER_REPORT.REPORT_CONTENT IS '신고내용';

COMMENT ON COLUMN USER_REPORT.USER_ID IS '신고자 아이디';

COMMENT ON COLUMN USER_REPORT.REG_DT IS '신고일시';

COMMENT ON COLUMN USER_REPORT.DISPOSITION IS '처분여부';

CREATE UNIQUE INDEX PK_USER_REPORT
	ON USER_REPORT (
		REPORT_NO ASC
	);

ALTER TABLE USER_REPORT
	ADD
		CONSTRAINT PK_USER_REPORT
		PRIMARY KEY (
			REPORT_NO
		);

/* 채팅방 */
CREATE TABLE CHATROOM (
	ROOM_NO INTEGER NOT NULL, /* 채팅방 번호 */
	SELLER_ID VARCHAR2(20) NOT NULL, /* 판매자 아이디 */
	BUYER_ID VARCHAR2(20) NOT NULL /* 구매자 아이디 */
);

COMMENT ON TABLE CHATROOM IS '채팅방';

COMMENT ON COLUMN CHATROOM.ROOM_NO IS '채팅방 번호';

COMMENT ON COLUMN CHATROOM.SELLER_ID IS '판매자 아이디';

COMMENT ON COLUMN CHATROOM.BUYER_ID IS '구매자 아이디';

CREATE UNIQUE INDEX PK_CHATROOM
	ON CHATROOM (
		ROOM_NO ASC
	);

ALTER TABLE CHATROOM
	ADD
		CONSTRAINT PK_CHATROOM
		PRIMARY KEY (
			ROOM_NO
		);

/* 게시판 */
CREATE TABLE BOARD (
	BOARD_NO INTEGER NOT NULL, /* 게시글 번호 */
	TAG VARCHAR2(5), /* 판매태그 */
	TITLE VARCHAR2(100), /* 게시글 제목 */
	CONTENT CLOB, /* 게시글 내용 */
	PRICE INTEGER, /* 희망가격 */
	GOODS_NAME VARCHAR2(30), /* 상품이름 */
	USER_ID VARCHAR2(20) NOT NULL, /* 작성자 아이디 */
	REG_DT DATE, /* 등록일시 */
	DELETE VARCHAR2(5), /* 삭제여부 */
	BLACKLIST VARCHAR2(5) /* 블랙리스트 처분 */
);

COMMENT ON TABLE BOARD IS '게시판';

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';

COMMENT ON COLUMN BOARD.TAG IS '판매태그';

COMMENT ON COLUMN BOARD.TITLE IS '게시글 제목';

COMMENT ON COLUMN BOARD.CONTENT IS '게시글 내용';

COMMENT ON COLUMN BOARD.PRICE IS '희망가격';

COMMENT ON COLUMN BOARD.GOODS_NAME IS '상품이름';

COMMENT ON COLUMN BOARD.USER_ID IS '작성자 아이디';

COMMENT ON COLUMN BOARD.REG_DT IS '등록일시';

COMMENT ON COLUMN BOARD.DELETE IS '삭제여부';

COMMENT ON COLUMN BOARD.BLACKLIST IS '블랙리스트 처분';

CREATE UNIQUE INDEX PK_BOARD
	ON BOARD (
		BOARD_NO ASC
	);

ALTER TABLE BOARD
	ADD
		CONSTRAINT PK_BOARD
		PRIMARY KEY (
			BOARD_NO
		);

/* 채팅내용 */
CREATE TABLE CHAT (
	CHAT_NO INTEGER NOT NULL, /* 채팅내용 번호 */
	ROOM_NO INTEGER NOT NULL, /* 채팅방 번호 */
	CONTENT CLOB, /* 채팅내용 */
	REG_DT DATE, /* 등록일시 */
	USER_ID VARCHAR2(20) NOT NULL /* 작성자 아이디 */
);

COMMENT ON TABLE CHAT IS '채팅내용';

COMMENT ON COLUMN CHAT.CHAT_NO IS '채팅내용 번호';

COMMENT ON COLUMN CHAT.ROOM_NO IS '채팅방 번호';

COMMENT ON COLUMN CHAT.CONTENT IS '채팅내용';

COMMENT ON COLUMN CHAT.REG_DT IS '등록일시';

COMMENT ON COLUMN CHAT.USER_ID IS '작성자 아이디';

CREATE UNIQUE INDEX PK_CHAT
	ON CHAT (
		CHAT_NO ASC
	);

ALTER TABLE CHAT
	ADD
		CONSTRAINT PK_CHAT
		PRIMARY KEY (
			CHAT_NO
		);

/* 공지사항 */
CREATE TABLE NOTICE (
	NOTICE_NO INTEGER NOT NULL, /* 공지사항 번호 */
	TITLE VARCHAR2(100), /* 공지사항 제목 */
	CONTENT CLOB, /* 공지사항 내용 */
	ADMIN_ID VARCHAR2(20) NOT NULL, /* 관리자 아이디 */
	REG_DT DATE, /* 등록일시 */
	DELETE VARCHAR2(5), /* 삭제여부 */
	POPUP VARCHAR2(5) /* 팝업여부 */
);

COMMENT ON TABLE NOTICE IS '공지사항';

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항 번호';

COMMENT ON COLUMN NOTICE.TITLE IS '공지사항 제목';

COMMENT ON COLUMN NOTICE.CONTENT IS '공지사항 내용';

COMMENT ON COLUMN NOTICE.ADMIN_ID IS '관리자 아이디';

COMMENT ON COLUMN NOTICE.REG_DT IS '등록일시';

COMMENT ON COLUMN NOTICE.DELETE IS '삭제여부';

COMMENT ON COLUMN NOTICE.POPUP IS '팝업여부';

CREATE UNIQUE INDEX PK_NOTICE
	ON NOTICE (
		NOTICE_NO ASC
	);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT PK_NOTICE
		PRIMARY KEY (
			NOTICE_NO
		);

/* 관심목록 */
CREATE TABLE INTEREST_LIST (
	INTEREST_NO INTEGER NOT NULL, /* 관심 번호 */
	USER_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	BOARD_NO INTEGER NOT NULL /* 게시글 번호 */
);

COMMENT ON TABLE INTEREST_LIST IS '관심목록';

COMMENT ON COLUMN INTEREST_LIST.INTEREST_NO IS '관심 번호';

COMMENT ON COLUMN INTEREST_LIST.USER_ID IS '회원 아이디';

COMMENT ON COLUMN INTEREST_LIST.BOARD_NO IS '게시글 번호';

CREATE UNIQUE INDEX PK_INTEREST_LIST
	ON INTEREST_LIST (
		INTEREST_NO ASC
	);

ALTER TABLE INTEREST_LIST
	ADD
		CONSTRAINT PK_INTEREST_LIST
		PRIMARY KEY (
			INTEREST_NO
		);

/* 게시글신고 */
CREATE TABLE BOARD_REPORT (
	REPORT_NO INTEGER NOT NULL, /* 신고 번호 */
	BOARD_NO INTEGER NOT NULL, /* 피신고 게시글 번호 */
	REPORT_CONTENT CLOB, /* 신고내용 */
	USER_ID VARCHAR2(20) NOT NULL, /* 신고자 아이디 */
	REG_DT DATE, /* 신고일시 */
	DISPOSITION VARCHAR2(5) /* 처분여부 */
);

COMMENT ON TABLE BOARD_REPORT IS '게시글신고';

COMMENT ON COLUMN BOARD_REPORT.REPORT_NO IS '신고 번호';

COMMENT ON COLUMN BOARD_REPORT.BOARD_NO IS '피신고 게시글 번호';

COMMENT ON COLUMN BOARD_REPORT.REPORT_CONTENT IS '신고내용';

COMMENT ON COLUMN BOARD_REPORT.USER_ID IS '신고자 아이디';

COMMENT ON COLUMN BOARD_REPORT.REG_DT IS '신고일시';

COMMENT ON COLUMN BOARD_REPORT.DISPOSITION IS '처분여부';

CREATE UNIQUE INDEX PK_BOARD_REPORT
	ON BOARD_REPORT (
		REPORT_NO ASC
	);

ALTER TABLE BOARD_REPORT
	ADD
		CONSTRAINT PK_BOARD_REPORT
		PRIMARY KEY (
			REPORT_NO
		);

/* 거래이력 */
CREATE TABLE TRADE_HISTORY (
	COL INTEGER NOT NULL, /* 거래 번호 */
	SELLER_ID VARCHAR2(20) NOT NULL, /* 판매자 아이디 */
	BUYER_ID VARCHAR2(20) NOT NULL, /* 구매자 아이디 */
	BOARD_NO INTEGER NOT NULL /* 게시글 번호 */
);

COMMENT ON TABLE TRADE_HISTORY IS '거래이력';

COMMENT ON COLUMN TRADE_HISTORY.COL IS '거래 번호';

COMMENT ON COLUMN TRADE_HISTORY.SELLER_ID IS '판매자 아이디';

COMMENT ON COLUMN TRADE_HISTORY.BUYER_ID IS '구매자 아이디';

COMMENT ON COLUMN TRADE_HISTORY.BOARD_NO IS '게시글 번호';

CREATE UNIQUE INDEX PK_TRADE_HISTORY
	ON TRADE_HISTORY (
		COL ASC
	);

ALTER TABLE TRADE_HISTORY
	ADD
		CONSTRAINT PK_TRADE_HISTORY
		PRIMARY KEY (
			COL
		);

/* 판매자신고2 */
CREATE TABLE USER_REPORT2 (
	REPORT_NO INTEGER NOT NULL, /* 신고 번호 */
	REPORT_CONTENT CLOB, /* 신고내용 */
	USER_ID VARCHAR2(20) NOT NULL, /* 신고자 아이디 */
	REG_DT DATE, /* 신고일시 */
	DISPOSITION VARCHAR2(5) /* 처분여부 */
);

COMMENT ON TABLE USER_REPORT2 IS '판매자신고2';

COMMENT ON COLUMN USER_REPORT2.REPORT_NO IS '신고 번호';

COMMENT ON COLUMN USER_REPORT2.REPORT_CONTENT IS '신고내용';

COMMENT ON COLUMN USER_REPORT2.USER_ID IS '신고자 아이디';

COMMENT ON COLUMN USER_REPORT2.REG_DT IS '신고일시';

COMMENT ON COLUMN USER_REPORT2.DISPOSITION IS '처분여부';

CREATE UNIQUE INDEX PK_USER_REPORT2
	ON USER_REPORT2 (
		REPORT_NO ASC
	);

ALTER TABLE USER_REPORT2
	ADD
		CONSTRAINT PK_USER_REPORT2
		PRIMARY KEY (
			REPORT_NO
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_USER_TO_REVIEW
		FOREIGN KEY (
			SELLER_ID
		)
		REFERENCES USER (
			USER_ID
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_USER_TO_REVIEW2
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USER (
			USER_ID
		);

ALTER TABLE USER_REPORT
	ADD
		CONSTRAINT FK_USER_TO_USER_REPORT
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USER (
			USER_ID
		);

ALTER TABLE CHATROOM
	ADD
		CONSTRAINT FK_USER_TO_CHATROOM
		FOREIGN KEY (
			SELLER_ID
		)
		REFERENCES USER (
			USER_ID
		);

ALTER TABLE CHATROOM
	ADD
		CONSTRAINT FK_USER_TO_CHATROOM2
		FOREIGN KEY (
			BUYER_ID
		)
		REFERENCES USER (
			USER_ID
		);

ALTER TABLE BOARD
	ADD
		CONSTRAINT FK_USER_TO_BOARD
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USER (
			USER_ID
		);

ALTER TABLE CHAT
	ADD
		CONSTRAINT FK_CHATROOM_TO_CHAT
		FOREIGN KEY (
			ROOM_NO
		)
		REFERENCES CHATROOM (
			ROOM_NO
		);

ALTER TABLE CHAT
	ADD
		CONSTRAINT FK_USER_TO_CHAT
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USER (
			USER_ID
		);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT FK_USER_TO_NOTICE
		FOREIGN KEY (
			ADMIN_ID
		)
		REFERENCES USER (
			USER_ID
		);

ALTER TABLE INTEREST_LIST
	ADD
		CONSTRAINT FK_USER_TO_INTEREST_LIST
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USER (
			USER_ID
		);

ALTER TABLE INTEREST_LIST
	ADD
		CONSTRAINT FK_BOARD_TO_INTEREST_LIST
		FOREIGN KEY (
			BOARD_NO
		)
		REFERENCES BOARD (
			BOARD_NO
		);

ALTER TABLE BOARD_REPORT
	ADD
		CONSTRAINT FK_BOARD_TO_BOARD_REPORT
		FOREIGN KEY (
			BOARD_NO
		)
		REFERENCES BOARD (
			BOARD_NO
		);

ALTER TABLE BOARD_REPORT
	ADD
		CONSTRAINT FK_USER_TO_BOARD_REPORT
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USER (
			USER_ID
		);

ALTER TABLE TRADE_HISTORY
	ADD
		CONSTRAINT FK_USER_TO_TRADE_HISTORY2
		FOREIGN KEY (
			SELLER_ID
		)
		REFERENCES USER (
			USER_ID
		);

ALTER TABLE TRADE_HISTORY
	ADD
		CONSTRAINT FK_USER_TO_TRADE_HISTORY
		FOREIGN KEY (
			BUYER_ID
		)
		REFERENCES USER (
			USER_ID
		);

ALTER TABLE TRADE_HISTORY
	ADD
		CONSTRAINT FK_BOARD_TO_TRADE_HISTORY
		FOREIGN KEY (
			BOARD_NO
		)
		REFERENCES BOARD (
			BOARD_NO
		);

ALTER TABLE USER_REPORT2
	ADD
		CONSTRAINT FK_USER_TO_USER_REPORT2
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USER (
			USER_ID
		);